### ISSUE TITLE
Add Namespace code for User entity in the example in the README.md file

### ISSUE THREAD

**Issue by jasondavis** [adespresso/FeatureBundle#35]
If you follow the installation instructions in the package `README.md` file to add  to a `User` model like this:  

    class User extends Authenticatable implements FeaturableInterface
    {
        use HasApiTokens, Notifiable, Auditable, UserHasTeams, Followable, Featurable;
    }

I get this error message:

    FatalErrorException in User.php line 19:
    Trait 'App\Models\Featurable' not found

Not sure if other had this issue but it might be worth adding the correct Namespace usage to the example in `README.md`.

---

To resolve my issue I have tried these in my User.php model file with no luck of any of them working.   Could someone post the correct value please and thanks....

    use LaravelFeature
    use LaravelFeature\Domain;
    use LaravelFeature\Featurable
    use LaravelFeature\Featurable\FeaturableInterface;

**Comment by francescomalatesta** [comment]
I see that you already opened in the right repository, please don't open new issues here for the Laravel package.
