### ISSUE TITLE
Distribution & versioning

### ISSUE THREAD

**Issue by EmanueleMinotto** [adespresso/FeatureBundle#4]
This bundle is not available on available on Packagist, can you add it @carlo1138?
Also imo it's ready for a `1.0.0` tag (to follow semver strictly), do you agree?

PS: is the related Wiki required?

**Comment by carlo1138** [comment]
> This bundle is not available on available on Packagist, can you add it @carlo1138?

Done.
https://packagist.org/packages/adespresso/feature-bundle

> Also imo it's ready for a 1.0.0 tag (to follow semver strictly), do you agree?

:+1:

**Comment by maxcanna** [comment]
Let's add some badges!
[![Latest Stable Version](https://poser.pugx.org/adespresso/feature-bundle/v/stable)](https://packagist.org/packages/adespresso/feature-bundle) [![Total Downloads](https://poser.pugx.org/adespresso/feature-bundle/downloads)](https://packagist.org/packages/adespresso/feature-bundle) [![Latest Unstable Version](https://poser.pugx.org/adespresso/feature-bundle/v/unstable)](https://packagist.org/packages/adespresso/feature-bundle) [![License](https://poser.pugx.org/adespresso/feature-bundle/license)](https://packagist.org/packages/adespresso/feature-bundle)
